# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Veto < Formula
  desc "Turn OpenAPI services into tools an agent can call under your rules."
  homepage "https://github.com/aiveto/veto"
  version "0.1.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aiveto/veto/releases/download/v0.1.2/veto_Darwin_x86_64.tar.gz"
      sha256 "a8a873f47fe5e078e3eff9479fb19c822e2cbe3d8a130cd62472a0e95c68bb9d"

      define_method(:install) do
        bin.install "veto"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aiveto/veto/releases/download/v0.1.2/veto_Darwin_arm64.tar.gz"
      sha256 "d5122a2876991bf3901d3cd43688a6a6b63c653ce2d3b088876323ff178ce6a6"

      define_method(:install) do
        bin.install "veto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aiveto/veto/releases/download/v0.1.2/veto_Linux_x86_64.tar.gz"
      sha256 "83bbefedfb102621b529eacf983e1e6f64ee4259c4f0dccd275994d3d17a2c72"
      define_method(:install) do
        bin.install "veto"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aiveto/veto/releases/download/v0.1.2/veto_Linux_arm64.tar.gz"
      sha256 "3bb54b32de1c4218c7ce7e94181438c587eb286e68524a16336ad704a607fff1"
      define_method(:install) do
        bin.install "veto"
      end
    end
  end

  test do
    system "#{bin}/veto", "--help"
  end
end
